[package]
name = "hello_clap"
authors = ["One_Ordinary_Man"]
description = "Hello world with clap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.2.7", features = ["derive"]}
